[build-system]
requires = ["setuptools >= 66.1.0", "setuptools_scm>=8"]  # minimum setuptools version supporting Python 3.12
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]

[tool.setuptools_scm]